apiversion: v1
kind: verify-report
metadata:
    tool:
        verifier-version: 1.0.0
        profile:
            VendorType: partner
            version: v1.1
        chart-uri: https://github.com/IBM/charts/raw/master/repo/ibm-helm/ibm-sfg-prod-2.1.0.tgz
        digests:
            chart: sha256:8726b1d6b743bec4f8d769772eb40232373ef29ef23c3a3ece76504057afad31
            package: 4761eced911a4b73df2c4087b5efbb6c13ded1dcb99c315c3efb0e3625e6c624
        lastCertifiedTimestamp: "2022-10-07T17:15:32.318057+05:30"
        testedOpenShiftVersion: N/A
        supportedOpenShiftVersions: '>=4.8'
        providerControlledDelivery: false
    chart:
        name: ibm-sfg-prod
        home: https://www.ibm.com/docs/en/b2b-integrator/6.1.2
        sources: []
        version: 2.1.0
        description: IBM Sterling File Gateway lets organizations transfer files between partners by using different protocols, conventions for naming files, and file formats. A scalable and security-enabled gateway, Sterling File Gateway enables companies to consolidate all their internet-based file transfers on a single edge gateway, which helps secure your B2B collaboration network and the data flowing through it. Documentation For additional details regarding install parameters check https://www.ibm.com/docs/en/b2b-integrator/6.1.2?topic=integrator-installing-sterling-b2b-using-certified-container. License By installing this product you accept the license terms http://www14.software.ibm.com/cgi-bin/weblap/lap.pl?li_formnum=L-MZIA-CCSKXJ&title=IBM%20Sterling%20File%20Gateway%20Certified%20Container%20V6.1.2"
        keywords:
            - sfg
            - b2b
            - mft
            - sterling
            - Commercial
            - amd64
            - ppc64le
            - s390x
            - Automation
            - RHOCP
            - Other
        maintainers:
            - name: IBM
              email: ""
              url: ""
        icon: https://raw.githubusercontent.com/IBM/charts/master/logo/ibm-sfg-icon.png
        apiversion: v2
        condition: ""
        tags: ""
        appversion: 6.1.2.0
        deprecated: false
        annotations: {}
        kubeversion: '>=1.21'
        dependencies:
            - name: ibm-sch
              version: 1.2.16
              repository: '@sch'
              condition: ""
              tags: []
              enabled: false
              importvalues: []
              alias: sch
        type: application
    chart-overrides: ""
results:
    - check: v1.0/images-are-certified
      type: Mandatory
      outcome: FAIL
      reason: 'Failed to certify images : Failed to get images, error running helm template : chart requires kubeVersion: >=1.21 which is incompatible with Kubernetes v1.20.0'
    - check: v1.0/contains-test
      type: Mandatory
      outcome: PASS
      reason: Chart test files exist
    - check: v1.0/contains-values-schema
      type: Mandatory
      outcome: PASS
      reason: Values schema file exist
    - check: v1.0/has-readme
      type: Mandatory
      outcome: PASS
      reason: Chart has a README
    - check: v1.0/helm-lint
      type: Mandatory
      outcome: PASS
      reason: Helm lint successful
    - check: v1.0/not-contain-csi-objects
      type: Mandatory
      outcome: PASS
      reason: CSI objects do not exist
    - check: v1.0/required-annotations-present
      type: Mandatory
      outcome: FAIL
      reason: 'Missing required annotations: [charts.openshift.io/name]'
    - check: v1.0/chart-testing
      type: Mandatory
      outcome: FAIL
      reason: 'Chart Install failure: failed pre-install: timed out waiting for the condition'
    - check: v1.0/contains-values
      type: Mandatory
      outcome: PASS
      reason: Values file exist
    - check: v1.0/is-helm-v3
      type: Mandatory
      outcome: PASS
      reason: API version is V2, used in Helm 3
    - check: v1.0/not-contains-crds
      type: Mandatory
      outcome: PASS
      reason: Chart does not contain CRDs
    - check: v1.1/has-kubeversion
      type: Mandatory
      outcome: PASS
      reason: Kubernetes version specified

