apiversion: v1
kind: verify-report
metadata:
    tool:
        verifier-version: 1.9.0
        profile:
            VendorType: partner
            version: v1.1
        reportDigest: uint64:11464294073087994648
        chart-uri: https://github.com/IBM/charts/raw/master/repo/ibm-helm/ibm-b2bi-prod-2.1.0.tgz
        digests:
            chart: sha256:8da0ee3ee68d6c2fb062932a5aadcdc31471168e0567720ddbd578e7dd965d7d
            package: e7929db4909c2537abf3a3e727046abde286b98ae0eaa5ecf2677ec241dde17d
        lastCertifiedTimestamp: "2022-10-04T13:47:00.958126+05:30"
        testedOpenShiftVersion: N/A
        supportedOpenShiftVersions: '>=4.8'
        providerControlledDelivery: false
    chart:
        name: ibm-b2bi-prod
        home: https://www.ibm.com/docs/en/b2b-integrator/6.1.2
        sources: []
        version: 2.1.0
        description: IBM Sterling B2B Integrator helps companies integrate complex B2B EDI processes with their partner communities. Organizations get a single, flexible B2B platform that supports most communication protocols, helps secure your B2B network and data, and achieves high-availability operations. The offering enables companies to reduce costs by consolidating EDI and non-EDI any-to-any transmissions on a single B2B platform and helps automate B2B processes across enterprises, while providing governance and visibility over those processes. Documentation For additional details regarding install parameters check https://www.ibm.com/docs/en/b2b-integrator/6.1.2?topic=integrator-installing-sterling-b2b-using-certified-container. License By installing this product you accept the license terms http://www14.software.ibm.com/cgi-bin/weblap/lap.pl?li_formnum=L-MZIA-CCSL2W&title=IBM%20Sterling%20B2B%20Integrator%20Certified%20Container%20V6.1.2"
        keywords:
            - b2bi
            - b2b
            - mft
            - sterling
            - Commercial
            - amd64
            - ppc64le
            - s390x
            - Automation
            - RHOCP
            - Other
        maintainers:
            - name: IBM
              email: ""
              url: ""
        icon: https://raw.githubusercontent.com/IBM/charts/master/logo/ibm-b2bi-icon.png
        apiversion: v2
        condition: ""
        tags: ""
        appversion: 6.1.2.0
        deprecated: false
        annotations: {}
        kubeversion: '>=1.21'
        dependencies:
            - name: ibm-sch
              version: 1.2.16
              repository: '@sch'
              condition: ""
              tags: []
              enabled: false
              importvalues: []
              alias: sch
        type: application
    chart-overrides: ""
results:
    - check: v1.0/contains-test
      type: Mandatory
      outcome: PASS
      reason: Chart test files exist
    - check: v1.0/contains-values-schema
      type: Mandatory
      outcome: PASS
      reason: Values schema file exist
    - check: v1.0/helm-lint
      type: Mandatory
      outcome: PASS
      reason: Helm lint successful
    - check: v1.0/required-annotations-present
      type: Mandatory
      outcome: FAIL
      reason: 'Missing required annotations: [charts.openshift.io/name]'
    - check: v1.0/not-contains-crds
      type: Mandatory
      outcome: PASS
      reason: Chart does not contain CRDs
    - check: v1.0/chart-testing
      type: Mandatory
      outcome: FAIL
      reason: 'Chart Install failure: failed pre-install: timed out waiting for the condition'
    - check: v1.0/contains-values
      type: Mandatory
      outcome: PASS
      reason: Values file exist
    - check: v1.1/has-kubeversion
      type: Mandatory
      outcome: PASS
      reason: Kubernetes version specified
    - check: v1.0/has-readme
      type: Mandatory
      outcome: PASS
      reason: Chart has a README
    - check: v1.0/images-are-certified
      type: Mandatory
      outcome: FAIL
      reason: 'Failed to certify images : Failed to get images, error running helm template : chart requires kubeVersion: >=1.21 which is incompatible with Kubernetes v1.20.0'
    - check: v1.0/is-helm-v3
      type: Mandatory
      outcome: PASS
      reason: API version is V2, used in Helm 3
    - check: v1.0/not-contain-csi-objects
      type: Mandatory
      outcome: PASS
      reason: CSI objects do not exist

